### ISSUE TITLE
tweak platform

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ec-earth-errata-tracer#1]
Here we can discuss how to design this EC-Earth errata-tracer platform.

The procedure how to handle incoming errata and how to trace and proceed as discussed in the June CMIP6 WG telco is added on the [procedure issue handling](https://github.com/EC-Earth/ec-earth-errata-tracer/wiki/procedure-issue-handling) wiki page, and can be improved.

Some first [README](https://github.com/EC-Earth/ec-earth-errata-tracer/blob/master/README.md) text is added, but feel free to improve.

**Comment by treerink** [comment]
Added some labels to trace the status as listed in the README. Are there better status tracing options with Github?

**Comment by goord** [comment]
I think this is fine Thomas
